Dockerfile, nuxt.config.js, package-lock.json, package.json, pages/README.md, pages/overlayspike.vue, plugins/global.js, tailwind.config.js
A hilariously simple example of an overlay form ... created it in its own little page .  something to check out for a laugh :)
=> adding vuetify and a quick overlay example

components/Forms/FilterForm.vue, pages/engagement/list/index.vue
Added a filter on fake data field called title. I also used a custom input instead of the component since I am not sure if we can use a component to emit the input inside the text field.
Please check out this PR and judge for yourselves if you would like to keep it before the folder re-structure.
=> Ben new search

nuxt.config.js, server/api/contact/index.js, server/api/models/contact.js
Initial API end points for contacts and contact model
=>  Initia; api end points for contacts

package-lock.json, package.json
I deleted nodemon while getting rid of extra babel dependencies. Very sorry :(
=> Adding nodemon

.eslintrc.js, components/layout/AppHeader.vue, server/api/contact/index.js, server/api/user/index.js, server/index.js, services/AxiosService.js, test/db/contact.test.js, test/db/engagement.test.js, tools/dbHelper.js, tools/seeder/seeder.js
updated linting config and any outstanding lint errors
get code - run: npm run lint
fix errors using: npm run lint -- --fix
=> fixing linting and lint config to match our decided standard

components/app/AppFilterForm.vue, components/app/AppNavBtn.vue, components/app/AppNavSearching.vue, components/engagement/EngListItem.vue, layouts/error.vue, nuxt.config.js, server/api/engagement/index.js
Added search functionality for field type ONLY.
Using seeder.
Added endpoint for engagements with the help of Kevin.
Added search functionality for each engagement.
The only field it searches on for now is 'type'.
The filtering event is on keyup.
This is only the functionality. 
There is no styling for the results and the search is only the field 'type'.
1. Go to home page.
2. type in the search bar what ever Type of Engagement you are looking for.
=> 107-search-engagements

components/app/AppNavBtn.vue, components/layout/AppFooterLinks.vue, components/layout/AppHeader.vue, cypress/integration/add-contact.spec.js, cypress/integration/add-engage.spec.js, cypress/integration/index.spec.js, cypress/integration/search-contact.spec.js, cypress/integration/search-engage.spec.js, cypress/integration/utils.js, cypress/support/index.js, lang/en-CA.js
Added e2e tests for the homepage items and links
runs in the pipeline. 
- Things that you (the submitter)...
- want reviewers to pay very close...
- attention to when they review this PR.
=> added new e2e tests

.github/pull_request_template.md
Added a checkbox in the PR template to confirm your code is ready for translations when you open your PR (If applicable). All strings should be interpolated with the i18n framework like this: `<p> {{ $t('component.stringName') }} </p>`, instead of hard coded: `<p> My Text </p>`
1. Open a Pull Request
1. Verify the checkbox exists
- If anybody has a more concise message to add instead of what I added, feel free to request it.
=> Translation checkbox

package.json
Running staging as a Node program instead of Nuxt until compilation is fixed
- Run the app with Nuxt, find out why it doesn't work, PR a solution
=> Temporary fix for staging start script

nuxt.config.js
Need to have the Axios baseURL variable parameterized for staging / prod deployments :+1:
=> Enabling env var for baseURL

.github/workflows/test.yml
Defines baseURL for Cypress running in e2e pipeline 
1. Create a pull request
1. Watch your E2E tests run
=> Added baseURL var for Cypress in testing pipeline

test/db/contact.test.js, test/db/engagement.test.js
Last PR had broken paths in the DB unit tests, this fixes those.
1. npm run test
1. tests will pass
=> Fixed broken paths for db unit tests

api/routes/contact.js, components/app/AppFilterForm.vue, components/engagement/EngShowContacts.vue, pages/search/contact.vue, pages/search/engagement.vue, pages/view/contact/_id.vue, tools/seeder/seeder.js
Completed story [#106](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/us/106?milestone=19).
Acceptance Criteria:
- User loads the home page and clicks the "Contact" search sub menu, all contacts are listed in alphabetical ascending order(by Contact Name) in the search results section and the search input field is in focus for user input
- User enters key words in search input, on each character entered(key up) search is performed on all contact data fields and matching results are displayed in search results section
- User clicks on a Contact in search results and the Contact detail view is displayed, clicks "Back to Results" and returns to contact search results page
1. npm run dev
1. see that it meets acceptance criteria
=> 106 Search Contacts

components/app/AppNavAdding.vue, components/contact/ContactForm.vue, components/engagement/EngForm.vue, lang/en-CA.js, pages/add/contact.vue, pages/add/engagement.vue
Added some styling to Add/Form pages for more consistency across the application.
1. Toggle between Engagement and Contact Add/Form pages
1. See that styling is consistent
- Let me know if there is any more that should be added
=> Modified styles for more consistency

components/contact/ContactForm.vue, components/engagement/EngForm.vue, components/engagement/EngShowContacts.vue, lang/en-CA.js, pages/view/contact/_id.vue
Contact Detail view will use data directly from vuex store.
1. Click on button to view Contact Detail
1. See Contact Details of selected contact
=> Configured Contact Detail view to get data from Vuex store

Jenkinsfile, helmfile/helmfile.yaml
Adding Jenkinsfile for automated deployments
Run jenkins deploy job
=> Jenkinsfile

components/contact/ConShowEngagements.vue, components/engagement/EngViewFields.vue, lang/en-CA.js, lang/fr-FR.js, pages/search/contact.vue, pages/search/engagement.vue, pages/view/engagement/_id.vue
Implemented Detail view for Engagements. This is only to show the data.
This has no styling to it... yet.
1. Navigate to search engagements and contacts. 
2. select an engagement and it should bring you to the view detail.
I believe I am using the state properly in engagement/_id. I copied what Jordan had done for contacts.
=> 109 engagement detail view

Jenkinsfile
Adding set +x on context script in jenkinsfile so Jenkins will not display the console output of that script.
=> obfuscating secrets

nuxt.config.js, pages/search/contact.vue, pages/search/engagement.vue
Added number of results on the search form 
should not blocked Ben's latest PR
1. Go to search page either contact or engagements
1. number of records should display the number of records on the list
1. type in search and the number of records should reflect the number of records on the list
=> 187 total records

components/contact/ContactForm.vue, components/engagement/EngForm.vue
Small fix to margin in the contact form and to font styles for both form titles.
1. Compare Engagement and Contact forms
1. See that h1 font styles and margins are consistent
=> Fixed margin for consistency

helmfile/overrides/frontend/rmp.yaml.gotmpl
Merging old change from MTS-Helm
=> Updating BASE_URL to VUE_API_URL

pages/view/engagement/_id.vue, store/contacts.js, tools/seeder/randomizers.js, tools/seeder/seeder.js
In the EngagementsDetailView, all contacts are fetched and that data is used to find the most recent Engagement for each of the contacts that the EngagementDetailView has in its ContactList and display the related information. Child engagements to Contacts data/documents are returned from the db in chronological order so it is a matter of just taking the element from the end of the array and passing it's values to the EngShowContacts component.
1. npm run mongodb
1. npm run seed
1. npm run dev
1. navigate to EngagementDetailView by selecting an Engagement in the EngagementList of the EngagementSearch
1. see that contact details for that engagement include details on the latest engagement
=> 206 Show most recent Engagement information in EngagementDetailView for each ContactListItem

.github/pull_request_template.md
An update to the PR template to include links to Taiga tasks and stories, as well as explicitly defining the acceptance criteria for related stories in the PR. Please take advantage and implement this information into your future PRs.
=> PR Template Configured to Support Acceptance Criteria and Links to Tasks+Stories

helmfile/scripts/dataseed.sh
Finalized fix on dataseed script
=> Troubleshooting dataseed script

components/engagement/EngComments.vue, pages/add/comment.vue, store/engagements.js
POC to add comments to an engagement
Task #229 vuex update to manage comments
1. goto test page /add/comment 
1. click on submit 
1. see changes in store.
1. use as example
=> 229 vuex comments

components/contact/ContactForm.vue
#216 After success fully saving new contact, contact form should be cleared to allow user to enter new contact.
show succesfull message clears the form 
1. Go to add a contact 
1. enter some valid data and submit 
1. after the successful message fade out the form is cleared
1. user stays on the form to enter a new contact if so he chooses
=> #216 clean after add

components/contact/ContactForm.vue, components/contact/ContactForm2.vue, components/engagement/EngForm.vue, components/engagement/EngSelectContacts.vue, plugins/vue2-editor.js, store/contacts.js, tools/seeder/randomizers.js
Removing unnecessary console logging that is plaguing our terminals.
Also found some unused code from a different project that has no use here other than throwing linter errors.
=> Removed all useless console logging and unused randomizer code

layouts/default.vue
Just adding 1 more criteria to this branch. Hides nav bar on dashboard.
=> Adding dashboard to this fix

pages/view/engagement/_id.vue
Task 270 - Update the date display to display one the date removing the time format 
1. Go to Search engagements
1. select one
1. on the view engagement scroll to the contacts 
1. the date should display only a date without the time as before
=>  updated date display on viewCard

lang/en-CA.js, lang/fr-FR.js, pages/view/engagement/_id.vue
Add style to the tags to make it look like actual tag instead of plain text. 
tags aligns horizontally 
- go to search engagement
- click on one of the engagement card (arrow button)
- check the tags in the engagement detail
=> 267 detail tags

lang/en-CA.js, lang/fr-FR.js, pages/dashboard.vue
[Fixing dashboard dropdowns/button and translation]
N/A
1. go to dashboard
2. See the dropdowns now have arrows and the button has the correct text (Download PDF)
3. See the translation between French and English for each drop-downs, title and button.
=> Fixed issues with dashboard and translation.

components/contact/ContactForm.vue, components/engagement/EngForm.vue, components/engagement/EngFormSelect.vue, components/engagement/EngSelectContacts.vue, lang/en-CA.js, lang/fr-FR.js
Updated Engagement Form to match Contact Form Css
Added Comment and Description Character Counter
Updated translation and placeholder
Align form margin to align with title
To do: Drop down of selected contact needs to be mobile friendly.
1. Go to Engagement Form
2. Check if Form is mobile friendly by adjusting the screen size
3.Test the Character Counter if the number is correct
=> Task265 CSS updating

package-lock.json, pages/view/engagement/_id.vue, tools/seeder/seeder.js
[281 Add class="break-normal" to the description and comment field]https://taiga.dts-stn.com/project/pond-knowlege-management-portal/task/281?kanban-status=72
Changed the engagement description seeder to have multiple strings instead of one 150 character string.
(Very very long words will still extend the page. See Test Instruction step 3 and Help Requested bellow).
N/A
1. Select any egagement and see the description wrap as the screen resolution changes.
2. Go to add engagement.
3. [BUG] Create an engagement with a very very very long word. (over 100 character) This will extend the page.
I would need enlightenment on how to solve the step number 3.
=> added break-normal and changed description seeder.

tools/seeder/randomizers.js, tools/seeder/seeder.js
Added a few arrays to the seeder
=>  added a few array to randomisers

Jenkinsfile, helmfile/context-prod.sh
=> Prod endpoints

Jenkinsfile
Debugging jenkinsfile for prod
=> Moving context scripts around in jenkinsfile

Jenkinsfile, helmfile/scripts/deleteDatabase.sh
=> Prodmigration
