tools/dbHelper.js

Minor bug in the seeder code stopping it from connecting to the staging database. Just needed the password interpolation piece from the main app :+1: 
1. Deploy the app to staging
1. execute `npm run seed`

quick fix for the seeder connection string

---

components/app/AppNavAdding.vue
components/app/AppNavBtn.vue
components/app/AppNavSearching.vue
components/contact/ContactForm.vue
components/engagement/EngForm.vue
components/engagement/EngSelectContacts.vue
components/layout/AppFooterLinks.vue
pages/index.vue
pages/search/engagement.vue
tailwind.config.js

Up until now there was no common source of truth for the fonts and styling within the application. With this PR, the fonts from the style guide have been added to the tailwind global theme config and can be called on an element's class attribute using "font-display" (for headers and display text) and "font-body" (for all content text). I have modified our two forms and related components to utilize this, but there are still fixes required in the application in other pages/components.
Also, the add new contact form has been added to the button toggle for the "Add" section of the app.
1. Inspect form pages to see 'Lato' and 'Noto' being used for the displayed text
and
1. Navigate to "Add Contacts & Engagements"
2. Clock "Contacts" on the button toggle
3. See contact form displayed

Added fonts to global theme + Added contact form component to toggle

---

components/app/AppFilterForm.vue
components/app/AppNavAdding.vue
components/app/AppNavSearching.vue
components/layout/AppFooterLinks.vue
components/layout/AppHeader.vue
components/layout/AppNavBtn.vue
lang/en-CA.js
lang/fr-FR.js
pages/dashboard.vue
pages/search/contact.vue

Change hard coded strings to use language toggle.
Change some font sizing in the header.
Change every link to target _blank.
Organised the add and search pages to look a little bit more alike.
I did not add translation for the dashboard since we do not know what are the final drop-down options.
For the header:
Text placeholder, dashboard and log out are bigger.
As for the rest, navigate through the website and notice the French to English toggle.

language-fix

---

api/models/engagement.js
test/db/engagement.test.js
tools/seeder/seeder.js

`subject` field was missing from the Engagements model. It is now added.
1. View model and seeder code
1. See that subject is now a field of the Engagements model and is seeded

Adding "subject" field to Engagements model

---

api/routes/contact.js
api/routes/engagement.js
pages/view/contact/_id.vue
pages/view/engagement/_id.vue

Allows deep navigation of contacts->engagements->contacts..etc starting from the Engagement or Contact search.
1. Navigate to the engagement or contact search pages and select a contact or engagement
1. In detail view, see related engagements or contacts and select one
1. In detail view, see related engagements or contacts and select one
1. etc.
- If the client has no connection whatsoever, the error will return in the try/catch block of fetch() in _id.vue and log out to the console. We will likely want to show an error page in this case. Ideas for implementation would be appreciated.

Deep Contact/Engagement navigation

---

components/app/AppEngConToggle.vue
components/app/AppNavAdding.vue
components/app/AppNavSearching.vue
components/contact/ConShowEngagements.vue
components/layout/AppHeader.vue
components/layout/AppNavBtn.vue
lang/en-CA.js
lang/fr-FR.js
pages/search/contact.vue
pages/search/engagement.vue

A few Changes:
1. The header text placeholder has been change to RMP for French and English.
2. Home button redirects to search/engagement.
3. AppNavButton is orange when selected. (Primary colour for selected)
4. Created component for the blue toggle between engagement and contacts.
5. Since engagement is default, it is now to the left.
Test respectively:
1. Toggle French and English and see the header title change.
2. Click home button and it should bring you to 'search/engagement'. (NOTICE: the buttons should be selected 
for search and engagement.)
3. Navigate through 'Search Contacts and Engagement' to 'Add Contacts and engagements' The colour should 
change to orange as selected.
4. & 5. Test the blue toggle and confirm that the right page is displayed. Engagement should be on the …

Styling and flow fixing. Branch: home-button-redirect

---

nuxt.config.js
store/engagements.js

Added dotenv to the nuxt.config. This ensures that both client and server use the same baseURL value as defined in your .env file `baseURL` variable. Without this, `process.env.baseURL` in the nuxt.config.js was always undefined in both dev and prod builds and was defaulted by axios to localhost:3000 regardless of your .env variable value. 
1. Add the variable and value `baseURL=http://localhost:3000` to your .env file
1. npm run mongodb
1. npm run seed
1. npm run dev
1. see that navigating to search returns data
1. close dev instance
1. change the variable and value `baseURL=http://localhost:3000` to `baseURL=http://localhost:4567`
1. npm run dev
1. see a connection refused error in the console when navigating to the search
1. revert variable and value to `baseURL=http://localhost:3000` …

Added dotenv for axios baseURL configuration in nuxt.config.js

---

api/models/engagement.js
tools/seeder/seeder.js

[Add engagement comments to seeding](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/task/241?kanban-status=72)
Changing the Engagements schema comments property to take an array of strings. Seeder will now populate each engagement with 2 comments.
[#109 View Engagement info detail view](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/us/109?milestone=20)
User performs Engagement search and clicks a engagement from the search results, all engagement details are displayed
User clicks "Back to Results" button and returns to Engagement search results
Mobile/Web layout match mockups
Exclusions:
No "Edit Engagement" button support
1. npm run mongodb
1. npm run seed
1. use Robo3T, Studio3T, Postman or your browser to see the comments under each Engagement …

Changed Engagements schema, 2 comments generated in seeder

---

components/app/AppEngConToggle.vue

The colour changes even though we stay on the same page. (example: To see, click contact twice)
simplified color updates by using class instead deleted all the data, created and methods.
#239 Blue toggle Engagement/Contact can be pressed twice and the colour changes
1. got to the home page 
1. click on the pill button, click again and keep clicking the color wont change IF you click on the same side of the pill

239 - fixed double click issue

---

components/layout/AppNavBtn.vue

[#240 [BUG] Home nav buttons with the home button. See description.](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/task/240?kanban-status=72)
This is a fix for a minor logic error. If you navigated to the add tab, then pressed the home button, the search page would render, but the nav bar would not update (the wrong `nuxt-link` element would stay highlighted)
[#240 [BUG] Home nav buttons with the home button. See description.](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/task/240?kanban-status=72)
BUG: No AC from PO
1. From the default page, navigate to the 'Add contacts & engagements' tab by clicking the 'Add contacts & engagements' button in the nav bar 
1. Press the home button (Picture of a house in the top left of the page)
1. Once the home …

#240 home nav buttons

---

tools/seeder/randomizers.js

'International Stakeholders' Engagement type has been added to the seeder.
1. See /tools/seeder/Randomizer.js randomType method now has 'International Stakeholders' as a possible value

Added Engagement type 'International Stakeholders' to seeder

---

layouts/default.vue

[[BUG] Only display Nav bar at appropriate times (See design)](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/task/258?kanban-status=74)
Changed the behaviour of the navigation bar to dynamically render based on weather or not your looking at a detailed view.
[238 Styling Updates](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/us/238?milestone=20)
General fixes. No written AC. Please compare with design and notes on Taiga task: [[BUG] Only display Nav bar at appropriate times (See design)](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/task/258?kanban-status=74)
1. Open the design and check the detailed contacts and engagements page to see the intended behaviour (No app nav bar on these pages)
1. launch the app, navigate to 'Search …

Stopped showing nav bar on detailed view pages

---

components/app/AppNavAdding.vue
components/contact/ConViewFields.vue
components/contact/ContactForm.vue
components/contact/ContactForm2.vue
components/engagement/EngForm.vue
components/engagement/EngViewFields.vue
pages/view/contact/_id.vue
pages/view/engagement/_id.vue

Updated mobile versins of the Add Contact, Edit Contact and buttons of the Add engagements 
#246[Bug] Mobile view Add engagement/contact 
https://taiga.dts-stn.com/project/pond-knowlege-management-portal/issue/246?kanban-status=99
CSS in div classes changes to have fields at full size when media screen is less than 768px
1. Go to Add contact  or Edit contact or Add engagements (for buttons only)
1. Change the screen size using dev tools to anything less than 768px (ipad)

 contact forms mobile version and btn size updated

---

components/engagement/EngForm.vue
lang/en-CA.js
lang/fr-FR.js
pages/view/engagement/_id.vue

[#255 [BUG] Detail and Edit field labels need to be differentiated](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/issue/255)
This PR adds separate labels for detail view and form views for Engagements.
1. Navigate to an Engagement detail view
1. See that Comments and Description labels no longer contain validation messages
1. Navigate to the Engagement form
1. See that Comments and Description labels contain validation messages

Differentiated edit and detail view labels

---

components/engagement/EngForm.vue
lang/en-CA.js
lang/fr-FR.js

These changes were wiped out in the last conflict merge. Adding them again.
1. Navigate to an Engagement detail view
1. See that Comments and Description labels no longer contain validation messages
1. Navigate to the Engagement form
1. See that Comments and Description labels contain validation messages

Differentiated edit and detail labels

---

components/contact/ContactForm.vue
components/contact/ContactForm2.vue
components/layout/AppHeader.vue

Currently the Canada log on the header is in the center of the page 
this fix the issue and removes the unnecessary a tag for the top of page 
###Task # 272
##Story Acceptance Criteria
n/a
1. Run the app logo should be on the top left side 
2 try to add a non-federal contact it should not fail with boolean cast error

 updated header logo

---

components/layout/AppFooterLinks.vue

[Footer links should not have a dot when in full width](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/issue/273?kanban-status=99)
Removed comma to fix bug.
N/A
1. Scroll to the bottom and see the links.

fixed footer

---

components/engagement/EngForm.vue

Clear input fields after submit the form (Basically took Marco's code for the contact form). 
Bug fixed: 'engagement created' message display twice after submitting the form
- Go to the engagement form
- Fill in required fields
- Click on the save button
- Input fields should be cleared
Took Marco's implementation for the contact form #126 
@will0684 @MarcoGoC @nghe0001 @bcloutier7 @andr0272 @shewood

Clear fields on submit

---

components/engagement/EngShowContacts.vue

Bug fixed: extra comma and white space after contact name if organization name or phone number doesn't exist.
Add color and underline on the clickable phone number and email
- go to search contact page
- checkout the contact cards 
- on the left side of the contact, for the one that doesn't have organization name, only contact name and title are displayed. 
@will0684 @MarcoGoC @shewood @nghe0001 @bcloutier7 @andr0272

extra comma on contact

---

components/contact/ConShowEngagements.vue
components/contact/ConViewFields.vue
components/engagement/EngViewFields.vue
pages/view/contact/_id.vue
pages/view/engagement/_id.vue

Task #268 View details not in bold fonts. Contact & Engagements updated to have similar styling Tags were modified as well to match viewCard and View engagements in mobile version
1. Go to search select an engagement to view
1. on another tab go to search and select a contact to view 
1. compare the styling of both pages at full and mobile versions

 View Contact, engagement, tags update

---

components/contact/ContactForm.vue

280 - bug - Contact Type dropdown in Contact Form is not getting translated strings 
Updated options names to have the same name as the language file
1. Go to add contact 
1. Contact Type must have the correct names as opposed to a string 'contact.federal' etc.

280 - Contact Type drop down fix

---

components/app/AppNotification.vue
components/contact/ContactForm.vue
components/contact/ContactForm2.vue
components/engagement/EngForm.vue
lang/en-CA.js
lang/fr-FR.js
layouts/default.vue
store/notifications.js

[226 Display success notification on details page](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/task/226?kanban-status=74)
Updated notification framework to use vuex. Works across pages without delaying navigation. **(Only for success messages)**
From: [115 View Engagement: Edit Mode](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/us/115?milestone=20)
User updates Engagement fields with valid user input and clicks submit, Engagement form is hidden and Engagement detail page is displayed with updated info and success prompt is displayed(toast message top of page? match strategy with Contact detail view)
1. Feature needs to be tested in 3 locations: Add contact page, Edit contact page, Add engagement page.
1. Follow the flow of each page (For Add …

226 notification

---

components/app/AppButton.vue
components/contact/ContactForm.vue
components/contact/ContactForm2.vue
components/engagement/EngForm.vue
pages/view/contact/_id.vue
pages/view/engagement/_id.vue

[287] https://taiga.dts-stn.com/project/pond-knowlege-management-portal/issue/287?kanban-status=101
[288] https://taiga.dts-stn.com/project/pond-knowlege-management-portal/issue/288?kanban-status=99
**Task 287**  
Buttons size across Add, View, and Edit (except engagement) were modified to have a common look and feel (size)
on mobile (iPhone 5S min size) and full view.
Padding on form were updated to have a consistent size as well 
**Task 288**
Error message box on mobile was changed to have full width when on mobile and 50% when min-width = 768px (iPad)
1. Go to Add (contact, and Engagement) scroll to the bottom of the page, 
using devTools to change to different mobile versions, inspect the size of the buttons
press enter to submit the form making sure required fields are not entered …

287 buttons size / 288 Error message box on mobile

---

components/engagement/EngForm.vue
components/engagement/EngSelectedContact.vue
components/engagement/EngShowContacts.vue
components/engagement/EngTags.vue
lang/en-CA.js

**Task 289** https://taiga.dts-stn.com/project/pond-knowlege-management-portal/issue/289?kanban-status=99
Updated the ContactSelected component to display middle section of data only on full size 
updated the css and classes to avoid double lines in between elements when more than one selected  
**Task 291** styling the Tags on mobile because when adding 3 it was running out of space, 
now the tags display vertically on mobile and in-line when on full size 
**Task 292** removed goBack after creating an engagement and added $v.reset to avoid errors on a clean form.
1. Steps to reproduce:
On mobile: Add a new Engagement, select one or more contacts to populate the contact list 
Expected Results:
Contact list items are fully visible
1. while on mobile add 2 or 3 tags. tags will now display …

289 contact list clipped on mobile / 291 tags styling on mobile

---

api/routes/engagement.js

/engagement/engagements endpoint now returns all Engagements in descending order by date (most recent first).
1. npm run dev on this branch
1. go to Engagements search and see Engagements are sorted by date descending

Added descending sort on dates during Engagements query

---

components/engagement/EngForm.vue
lang/en-CA.js
lang/fr-FR.js

Add a button to the tag field, user can now click the button to add tags
- go to the enagegment form
- click on the + button to add tags
@bcloutier7 @will0684 @MarcoGoC @shewood @andr0272 @nghe0001

button to add tag

---

components/engagement/EngSelectedContact.vue

long titles or email address push the gargaba can out of view, still looks bad, but
1. Go to Add or Edit engagements on mobile select a contact with a long name or email 
1. everything wraps but garbage can is still visible

 289 - added breal to avoid long titles to push garbage icon out of view

---

components/engagement/EngSelectedContact.vue

for some reason while fighting with the linting the break-all was lost 
re-adding it 
1. Go to Add or Edit engagements on mobile select a contact with a long name or email
everything wraps but garbage can is still visible

 re-added break-all to avoid long titles to push garbage icon out of view

---

package-lock.json
pages/search/engagement.vue
tools/seeder/seeder.js

[[Bug] #309 Engagement Search does not support tags](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/task/309?kanban-status=72)
[[Bug] #310 Engagement search by contact name](https://taiga.dts-stn.com/project/pond-knowlege-management-portal/task/310?kanban-status=72)
Engagement search now supports searching over tags and contacts keyContactName.
1. Search for engagements by tag
1. Search for engagements by contact

Engagement search now iterates over tags and contact names

---

components/engagement/EngEditForm.vue

Task 313
re - added css for Error Message Box so that it is full width on mobile on Edit Engagement
=> Sheila noticed this bug first
1. Go to edit and engagement, delete the subject and submit 
1. on mobile the error message should be full width

313 error message Box size on mobile

---

lang/en-CA.js
tools/seeder/randomizers.js

This ensures the Engagement type dropdown is populated when editing.
1. View engagement and select Edit
1. See Engagement Type dropdown is populated
- If I missed a string let me know

Match "engagement type" strings in seeder and frontend

---

components/engagement/EngEditForm.vue
components/engagement/EngForm.vue

fix the style on buttons in edit engagement
- go to edit engagement page
- scroll to the bottom of the page
- compare 'cancel' and 'save' buttons with the buttons on other pages, style should be the same (used to be a gap between the buttons)
@will0684 @MarcoGoC @shewood @bcloutier7 @andr0272 @nghe0001

fix space between buttons

---

tools/seeder/seeder.js

As nice as having actual names for the contacts was, it causes issues with selecting a contact from the dropdown during the creation of engagements because it appears it is adding contacts to the engagement by name, rather than index in the array. This is causing issues when you try to add a contact for which there exists another contact with the same name. When you select this contact, both contacts will be added and validation becomes confused.
To workaround this issue, contact names will now have a random digit between 1 and 100 appended to the end.
1. On main, go to Engagements creation and select a contact name with duplicates
1. See that multiple contacts with that name are added simultaneously
1. On this branch, go to Engagements creation and select a contact (there will be no …

Append contact names with random int
